name: Run Parser Test

on:
  push:
    branches:
      - main

jobs:
  run_parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Hello
        run: echo "Hello, GitHub Actions!"
